### GEt /
GET http://localhost:5000/

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "vinay66@gmal.com",
  "password": "123123"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json  

{
  "username": "vinay66@gmal.com",
  "password": "123123"
}
### fetch todos get todos
GET http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzU5NTY4MzcwLCJleHAiOjE3NTk2NTQ3NzB9.GhemYYHHUoD6IoPln40SZhoUIp3X9j8VfkzSLqLXKog
### create todo - POST
POST http://localhost:5000/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzU5NTY4MzcwLCJleHAiOjE3NTk2NTQ3NzB9.GhemYYHHUoD6IoPln40SZhoUIp3X9j8VfkzSLqLXKog
Content-Type: application/json

{
  "task": "Buy milk"
}

### update todo - PUT
PUT http://localhost:5000/todos/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzU5NTY4MzcwLCJleHAiOjE3NTk2NTQ3NzB9.GhemYYHHUoD6IoPln40SZhoUIp3X9j8VfkzSLqLXKog
Content-Type: application/json

{

  "completed": true 
}

### delete todo - DELETE
DELETE http://localhost:5000/todos/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzU5NTY4MzcwLCJleHAiOjE3NTk2NTQ3NzB9.GhemYYHHUoD6IoPln40SZhoUIp3X9j8VfkzSLqLXKog