### GEt /
GET https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/

###
POST https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/auth/register
Content-Type: application/json

{
  "username": "vinay66@gmal.com",
  "password": "123123"
}

###
POST https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/auth/login
Content-Type: application/json  

{
  "username": "vinay66@gmal.com",
  "password": "123123"
}
### fetch todos get todos
GET https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5MjI1MzE0LCJleHAiOjE3NTkzMTE3MTR9.BGarQZcWZHIZqbq2b1QHG--W4McybyWiBx33aoOGOxo
### create todo - POST
POST https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5MjI1MzE0LCJleHAiOjE3NTkzMTE3MTR9.BGarQZcWZHIZqbq2b1QHG--W4McybyWiBx33aoOGOxo
Content-Type: application/json

{
  "task": "Buy milk"
}

### update todo - PUT
PUT https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/todos/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5MjI1MzE0LCJleHAiOjE3NTkzMTE3MTR9.BGarQZcWZHIZqbq2b1QHG--W4McybyWiBx33aoOGOxo
{
  "completed": true 
}

### delete todo - DELETE
DELETE https://todo-m13aqj2pn-yc-directorys-projects-c68fc445.vercel.app/todos/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU5MjI1MzE0LCJleHAiOjE3NTkzMTE3MTR9.BGarQZcWZHIZqbq2b1QHG--W4McybyWiBx33aoOGOxo